import { NextRequest, NextResponse } from 'next/server';
import { setAuthCookies, ensureUserColumn, getUsers, saveUsers } from '@/lib/auth-helpers';
import * as fs from 'fs';
import * as path from 'path';

// ── Invite validation ─────────────────────────────────────────────────────────
// Invite codes live in data/invites.json — managed by `npm run gen-invite`.
// Each code is single-use and time-limited. Expired / used codes are pruned on read.

interface Invite {
  code: string;
  createdAt: string;
  expiresAt: string;
  label?: string;
}

function consumeInvite(code: string): boolean {
  const invitesFile = path.join(process.cwd(), 'data', 'invites.json');
  if (!fs.existsSync(invitesFile)) return false;

  let invites: Invite[];
  try {
    invites = JSON.parse(fs.readFileSync(invitesFile, 'utf8'));
  } catch {
    return false;
  }

  const now = Date.now();
  // Purge expired codes while we're here
  const active = invites.filter(i => new Date(i.expiresAt).getTime() > now);
  const idx = active.findIndex(i => i.code === code);
  if (idx === -1) return false; // not found or expired

  // Remove the matched code — single use
  active.splice(idx, 1);
  fs.writeFileSync(invitesFile, JSON.stringify(active, null, 2), { mode: 0o600 });
  return true;
}

// ── POST /api/auth/register ───────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  // Master switch: INVITE_CODE env var must exist (its value no longer matters —
  // real codes are generated by `npm run gen-invite` and stored in data/invites.json)
  if (!process.env.INVITE_CODE) {
    return NextResponse.json({ error: 'Registration is not enabled on this server.' }, { status: 403 });
  }

  const { username, token, inviteCode } = await req.json();

  if (!inviteCode || !consumeInvite(String(inviteCode).trim())) {
    return NextResponse.json({ error: 'Invalid or expired invite code.' }, { status: 401 });
  }

  const cleanUsername = String(username ?? '').trim();
  if (cleanUsername.length < 2) {
    return NextResponse.json({ error: 'Username must be at least 2 characters.' }, { status: 400 });
  }
  if (!/^[a-zA-Z0-9_\-. ]+$/.test(cleanUsername)) {
    return NextResponse.json({ error: 'Username may only contain letters, numbers, spaces, hyphens, underscores and dots.' }, { status: 400 });
  }
  if (!token || String(token).length < 8) {
    return NextResponse.json({ error: 'Password must be at least 8 characters.' }, { status: 400 });
  }

  const users = getUsers();
  if (users.some(u => u.username.toLowerCase() === cleanUsername.toLowerCase())) {
    return NextResponse.json({ error: 'That username is already taken.' }, { status: 409 });
  }

  // Add user, persist to disk, update live process (no restart needed)
  users.push({ username: cleanUsername, token: String(token) });
  try {
    saveUsers(users);
  } catch {
    return NextResponse.json({ error: 'Could not save user — check server permissions.' }, { status: 500 });
  }

  await ensureUserColumn(cleanUsername);

  const response = NextResponse.json({ ok: true });
  setAuthCookies(response, String(token), cleanUsername);
  return response;
}
